siguel: Comando/executa_comando.o Estruturas/Árvore/arvore.o Estruturas/Fila/fila.o Estruturas/Hash/hashtable.o Estruturas/Item/item.o Estruturas/Lista/lista.o Estruturas/Merge/mergesort.o Formas/Anotação/anotacao.o Formas/Círculo/circulo.o Formas/Retângulo/retangulo.o Funções/funcoes.o Funções/parproximo.o Objetos/Comércio/comercio.o Objetos/Hidrante/hidrante.o Objetos/Pessoa/pessoa.o Objetos/Quadra/quadra.o Objetos/Rádiobase/radiobase.o Objetos/Semáforo/semaforo.o Parâmetros/parametros.o main.o
	gcc Comando/executa_comando.o Estruturas/Árvore/arvore.o Estruturas/Fila/fila.o Estruturas/Hash/hashtable.o Estruturas/Item/item.o Estruturas/Lista/lista.o Estruturas/Merge/mergesort.o Formas/Anotação/anotacao.o Formas/Círculo/circulo.o Formas/Retângulo/retangulo.o Funções/funcoes.o Funções/parproximo.o Objetos/Comércio/comercio.o Objetos/Hidrante/hidrante.o Objetos/Pessoa/pessoa.o Objetos/Quadra/quadra.o Objetos/Rádiobase/radiobase.o Objetos/Semáforo/semaforo.o Parâmetros/parametros.o main.o -lm -o siguel -g -pedantic -fstack-protector-all -std=c99

Comando/executa_comando.o: Comando/executa_comando.c Comando/executa_comando.h
	gcc -c Comando/executa_comando.c -lm -o Comando/executa_comando.o -g -pedantic -fstack-protector-all -std=c99

Estruturas/Árvore/arvore.o: Estruturas/Árvore/arvore.c Estruturas/Árvore/arvore.h	
	gcc -c Estruturas/Árvore/arvore.c -lm -o Estruturas/Árvore/arvore.o -g -pedantic -fstack-protector-all -std=c99

Estruturas/Fila/fila.o: Estruturas/Fila/fila.c Estruturas/Fila/fila.h	
	gcc -c Estruturas/Fila/fila.c -lm -o Estruturas/Fila/fila.o -g -pedantic -fstack-protector-all -std=c99

Estruturas/Hash/hashtable.o: Estruturas/Hash/hashtable.c Estruturas/Hash/hashtable.h	
	gcc -c Estruturas/Hash/hashtable.c -lm -o Estruturas/Hash/hashtable.o -g -pedantic -fstack-protector-all -std=c99

Estruturas/Item/item.o: Estruturas/Item/item.c Estruturas/Item/item.h	
	gcc -c Estruturas/Item/item.c -lm -o Estruturas/Item/item.o -g -pedantic -fstack-protector-all -std=c99

Estruturas/Lista/lista.o: Estruturas/Lista/lista.c Estruturas/Lista/lista.h	
	gcc -c Estruturas/Lista/lista.c -lm -o Estruturas/Lista/lista.o -g -pedantic -fstack-protector-all -std=c99

Estruturas/Merge/mergesort.o: Estruturas/Merge/mergesort.c Estruturas/Merge/mergesort.h	
	gcc -c Estruturas/Merge/mergesort.c -lm -o Estruturas/Merge/mergesort.o -g -pedantic -fstack-protector-all -std=c99

Formas/Anotação/anotacao.o: Formas/Anotação/anotacao.c Formas/Anotação/anotacao.h		
	gcc -c Formas/Anotação/anotacao.c -lm -o Formas/Anotação/anotacao.o -g -pedantic -fstack-protector-all -std=c99

Formas/Círculo/circulo.o: Formas/Círculo/circulo.c Formas/Círculo/circulo.h	
	gcc -c Formas/Círculo/circulo.c -lm -o Formas/Círculo/circulo.o -g -pedantic -fstack-protector-all -std=c99

Formas/Retângulo/retangulo.o: Formas/Retângulo/retangulo.c Formas/Retângulo/retangulo.h 	
	gcc -c Formas/Retângulo/retangulo.c -lm -o Formas/Retângulo/retangulo.o -g -pedantic -fstack-protector-all -std=c99

Funções/funcoes.o: Funções/funcoes.c Funções/funcoes.h
	gcc -c Funções/funcoes.c -lm -o Funções/funcoes.o -g -pedantic -fstack-protector-all -std=c99

Funções/parproximo.o: Funções/parproximo.c Funções/parproximo.h
	gcc -c Funções/parproximo.c -lm -o Funções/parproximo.o -g -pedantic -fstack-protector-all -std=c99

Objetos/Comércio/comercio.o: Objetos/Comércio/comercio.c Objetos/Comércio/comercio.h
	gcc -c Objetos/Comércio/comercio.c -lm -o Objetos/Comércio/comercio.o -g -pedantic -fstack-protector-all -std=c99

Objetos/Hidrante/hidrante.o: Objetos/Hidrante/hidrante.c Objetos/Hidrante/hidrante.h
	gcc -c Objetos/Hidrante/hidrante.c -lm -o Objetos/Hidrante/hidrante.o -g -pedantic -fstack-protector-all -std=c99

Objetos/Pessoa/pessoa.o: Objetos/Pessoa/pessoa.c Objetos/Pessoa/pessoa.h
	gcc -c Objetos/Pessoa/pessoa.c -lm -o Objetos/Pessoa/pessoa.o -g -pedantic -fstack-protector-all -std=c99

Objetos/Quadra/quadra.o: Objetos/Quadra/quadra.c Objetos/Quadra/quadra.h
	gcc -c Objetos/Quadra/quadra.c -lm -o Objetos/Quadra/quadra.o -g -pedantic -fstack-protector-all -std=c99

Objetos/Rádiobase/radiobase.o: Objetos/Rádiobase/radiobase.c Objetos/Rádiobase/radiobase.h
	gcc -c Objetos/Rádiobase/radiobase.c -lm -o Objetos/Rádiobase/radiobase.o -g -pedantic -fstack-protector-all -std=c99

Objetos/Semáforo/semaforo.o: Objetos/Semáforo/semaforo.c Objetos/Semáforo/semaforo.h
	gcc -c Objetos/Semáforo/semaforo.c -lm -o Objetos/Semáforo/semaforo.o -g -pedantic -fstack-protector-all -std=c99

Parâmetros/parametros.o: Parâmetros/parametros.c Parâmetros/parametros.h
	gcc -c Parâmetros/parametros.c -lm -o Parâmetros/parametros.o -g -pedantic -fstack-protector-all -std=c99

main.o: main.c
	gcc -c main.c -lm -o main.o -g -pedantic -fstack-protector-all -std=c99

clean: 
	rm -rf Comando/executa_comando.o Estruturas/Árvore/arvore.o Estruturas/Fila/fila.o Estruturas/Hash/hashtable.o Estruturas/Item/item.o Estruturas/Lista/lista.o Estruturas/Merge/mergesort.o Formas/Anotação/anotacao.o Formas/Círculo/circulo.o Formas/Retângulo/retangulo.o Funções/funcoes.o Funções/parproximo.o Objetos/Comércio/comercio.o Objetos/Hidrante/hidrante.o Objetos/Pessoa/pessoa.o Objetos/Quadra/quadra.o Objetos/Rádiobase/radiobase.o Objetos/Semáforo/semaforo.o Parâmetros/parametros.o main.o siguel vgcore.*