siguel: Comando/executa_comando.o Estruturas/ArquivoBin/arquivobin.o Estruturas/Arvore/arvore.o Estruturas/ArvoreB/arvoreb.o Estruturas/Fila/fila.o Estruturas/Hash/hashtable.o Estruturas/Item/item.o Estruturas/Lista/lista.o Estruturas/Merge/mergesort.o Estruturas/Grafo/grafo.o Estruturas/Registrador/registrador.o Formas/Anotacao/anotacao.o Formas/Grafo_Forma/grafo_forma.o Formas/Circulo/circulo.o Formas/Retangulo/retangulo.o Funcoes/funcoes.o Funcoes/parproximo.o Objetos/Comercio/comercio.o Objetos/Hidrante/hidrante.o Objetos/Pessoa/pessoa.o Objetos/Quadra/quadra.o Objetos/Radiobase/radiobase.o Objetos/Semaforo/semaforo.o Objetos/Carro/carro.o Parametros/parametros.o main.o
	gcc Comando/executa_comando.o Estruturas/ArquivoBin/arquivobin.o Estruturas/Arvore/arvore.o Estruturas/ArvoreB/arvoreb.o Estruturas/Fila/fila.o Estruturas/Hash/hashtable.o Estruturas/Item/item.o Estruturas/Lista/lista.o Estruturas/Merge/mergesort.o Estruturas/Grafo/grafo.o Estruturas/Registrador/registrador.o Formas/Anotacao/anotacao.o Formas/Grafo_Forma/grafo_forma.o Formas/Circulo/circulo.o Formas/Retangulo/retangulo.o Funcoes/funcoes.o Funcoes/parproximo.o Objetos/Comercio/comercio.o Objetos/Hidrante/hidrante.o Objetos/Pessoa/pessoa.o Objetos/Quadra/quadra.o Objetos/Radiobase/radiobase.o Objetos/Semaforo/semaforo.o Objetos/Carro/carro.o Parametros/parametros.o main.o -lm -o siguel -g -pedantic -fstack-protector-all -std=c99

Comando/executa_comando.o: Comando/executa_comando.c Comando/executa_comando.h
	gcc -c Comando/executa_comando.c -lm -o Comando/executa_comando.o -g -pedantic -fstack-protector-all -std=c99

Estruturas/ArquivoBin/arquivobin.o: Estruturas/ArquivoBin/arquivobin.c Estruturas/ArquivoBin/arquivobin.h	
	gcc -c Estruturas/ArquivoBin/arquivobin.c -lm -o Estruturas/ArquivoBin/arquivobin.o -g -pedantic -fstack-protector-all -std=c99

Estruturas/Arvore/arvore.o: Estruturas/Arvore/arvore.c Estruturas/Arvore/arvore.h	
	gcc -c Estruturas/Arvore/arvore.c -lm -o Estruturas/Arvore/arvore.o -g -pedantic -fstack-protector-all -std=c99

Estruturas/ArvoreB/arvoreb.o: Estruturas/ArvoreB/arvoreb.c Estruturas/ArvoreB/arvoreb.h
	gcc -c Estruturas/ArvoreB/arvoreb.c -lm -o Estruturas/ArvoreB/arvoreb.o -g -pedantic -fstack-protector-all -std=c99

Estruturas/Fila/fila.o: Estruturas/Fila/fila.c Estruturas/Fila/fila.h	
	gcc -c Estruturas/Fila/fila.c -lm -o Estruturas/Fila/fila.o -g -pedantic -fstack-protector-all -std=c99

Estruturas/Hash/hashtable.o: Estruturas/Hash/hashtable.c Estruturas/Hash/hashtable.h	
	gcc -c Estruturas/Hash/hashtable.c -lm -o Estruturas/Hash/hashtable.o -g -pedantic -fstack-protector-all -std=c99

Estruturas/Item/item.o: Estruturas/Item/item.c Estruturas/Item/item.h	
	gcc -c Estruturas/Item/item.c -lm -o Estruturas/Item/item.o -g -pedantic -fstack-protector-all -std=c99

Estruturas/Lista/lista.o: Estruturas/Lista/lista.c Estruturas/Lista/lista.h	
	gcc -c Estruturas/Lista/lista.c -lm -o Estruturas/Lista/lista.o -g -pedantic -fstack-protector-all -std=c99

Estruturas/Merge/mergesort.o: Estruturas/Merge/mergesort.c Estruturas/Merge/mergesort.h	
	gcc -c Estruturas/Merge/mergesort.c -lm -o Estruturas/Merge/mergesort.o -g -pedantic -fstack-protector-all -std=c99

Estruturas/Grafo/grafo.o: Estruturas/Grafo/grafo.c Estruturas/Grafo/grafo.h	
	gcc -c Estruturas/Grafo/grafo.c -lm -o Estruturas/Grafo/grafo.o -g -pedantic -fstack-protector-all -std=c99

Estruturas/Registrador/registrador.o: Estruturas/Registrador/registrador.c Estruturas/Registrador/registrador.h	
	gcc -c Estruturas/Registrador/registrador.c -lm -o Estruturas/Registrador/registrador.o -g -pedantic -fstack-protector-all -std=c99

Formas/Anotacao/anotacao.o: Formas/Anotacao/anotacao.c Formas/Anotacao/anotacao.h		
	gcc -c Formas/Anotacao/anotacao.c -lm -o Formas/Anotacao/anotacao.o -g -pedantic -fstack-protector-all -std=c99

Formas/Grafo_Forma/grafo_forma.o: Formas/Grafo_Forma/grafo_forma.c Formas/Grafo_Forma/grafo_forma.h		
	gcc -c Formas/Grafo_Forma/grafo_forma.c -lm -o Formas/Grafo_Forma/grafo_forma.o -g -pedantic -fstack-protector-all -std=c99

Formas/Circulo/circulo.o: Formas/Circulo/circulo.c Formas/Circulo/circulo.h	
	gcc -c Formas/Circulo/circulo.c -lm -o Formas/Circulo/circulo.o -g -pedantic -fstack-protector-all -std=c99

Formas/Retangulo/retangulo.o: Formas/Retangulo/retangulo.c Formas/Retangulo/retangulo.h 	
	gcc -c Formas/Retangulo/retangulo.c -lm -o Formas/Retangulo/retangulo.o -g -pedantic -fstack-protector-all -std=c99

Funcoes/funcoes.o: Funcoes/funcoes.c Funcoes/funcoes.h
	gcc -c Funcoes/funcoes.c -lm -o Funcoes/funcoes.o -g -pedantic -fstack-protector-all -std=c99

Funcoes/parproximo.o: Funcoes/parproximo.c Funcoes/parproximo.h
	gcc -c Funcoes/parproximo.c -lm -o Funcoes/parproximo.o -g -pedantic -fstack-protector-all -std=c99

Objetos/Comercio/comercio.o: Objetos/Comercio/comercio.c Objetos/Comercio/comercio.h
	gcc -c Objetos/Comercio/comercio.c -lm -o Objetos/Comercio/comercio.o -g -pedantic -fstack-protector-all -std=c99

Objetos/Hidrante/hidrante.o: Objetos/Hidrante/hidrante.c Objetos/Hidrante/hidrante.h
	gcc -c Objetos/Hidrante/hidrante.c -lm -o Objetos/Hidrante/hidrante.o -g -pedantic -fstack-protector-all -std=c99

Objetos/Pessoa/pessoa.o: Objetos/Pessoa/pessoa.c Objetos/Pessoa/pessoa.h
	gcc -c Objetos/Pessoa/pessoa.c -lm -o Objetos/Pessoa/pessoa.o -g -pedantic -fstack-protector-all -std=c99

Objetos/Quadra/quadra.o: Objetos/Quadra/quadra.c Objetos/Quadra/quadra.h
	gcc -c Objetos/Quadra/quadra.c -lm -o Objetos/Quadra/quadra.o -g -pedantic -fstack-protector-all -std=c99

Objetos/Radiobase/radiobase.o: Objetos/Radiobase/radiobase.c Objetos/Radiobase/radiobase.h
	gcc -c Objetos/Radiobase/radiobase.c -lm -o Objetos/Radiobase/radiobase.o -g -pedantic -fstack-protector-all -std=c99

Objetos/Semaforo/semaforo.o: Objetos/Semaforo/semaforo.c Objetos/Semaforo/semaforo.h
	gcc -c Objetos/Semaforo/semaforo.c -lm -o Objetos/Semaforo/semaforo.o -g -pedantic -fstack-protector-all -std=c99

Objetos/Carro/carro.o: Objetos/Carro/carro.c Objetos/Carro/carro.h
	gcc -c Objetos/Carro/carro.c -lm -o Objetos/Carro/carro.o -g -pedantic -fstack-protector-all -std=c99
	
Parametros/parametros.o: Parametros/parametros.c Parametros/parametros.h
	gcc -c Parametros/parametros.c -lm -o Parametros/parametros.o -g -pedantic -fstack-protector-all -std=c99

main.o: main.c
	gcc -c main.c -lm -o main.o -g -pedantic -fstack-protector-all -std=c99

clean: 
	rm -rf Comando/executa_comando.o Estruturas/ArquivoBin/arquivobin.o Estruturas/Arvore/arvore.o Estruturas/ArvoreB/arvoreb.o Estruturas/Fila/fila.o Estruturas/Hash/hashtable.o Estruturas/Item/item.o Estruturas/Lista/lista.o Estruturas/Merge/mergesort.o Estruturas/Grafo/grafo.o Estruturas/Registrador/registrador.o Formas/Anotacao/anotacao.o Formas/Circulo/circulo.o Formas/Retangulo/retangulo.o Funcoes/funcoes.o Funcoes/parproximo.o Objetos/Comercio/comercio.o Objetos/Hidrante/hidrante.o Objetos/Pessoa/pessoa.o Objetos/Quadra/quadra.o Objetos/Radiobase/radiobase.o Objetos/Semaforo/semaforo.o Objetos/Carro/carro.o Parametros/parametros.o Formas/Grafo_Forma/grafo_forma.o main.o siguel vgcore.* Arquivos/Saidas/* && touch Arquivos/Saidas/.a